<#
.SYNOPSIS
  AI Family - render the daily Briefing v2 (a decision tool, not a status dump).
.EXAMPLE
  ./send-family-briefing.ps1
#>
[CmdletBinding()]
param()

. "$PSScriptRoot/_Common.ps1"
$ctx = Initialize-Family
$today = Get-Date -Format 'yyyy-MM-dd'
$cfg = $ctx.Config

$sb = New-Object System.Text.StringBuilder
function Line($t = '') { [void]$sb.AppendLine($t) }

Line "# AI FAMILY BRIEFING - $today"
Line ""
Line "## 1 | DECISIONS (<=5)  - each: my recommendation + <approve/hold>"
$decided = $false
foreach ($e in @($cfg.episodes | Where-Object { $_.status -eq 'review' })) {
    Line ("- **D:** Publish ``$($e.id)`` *$($e.title)*?  -> REC ship to $($e.publish_targets -join ', ')  <approve/hold>")
    $decided = $true
}
foreach ($s in @($cfg.signals | Where-Object { $_.priority -eq 'P1' -and $_.status -eq 'new' })) {
    $a = Find-Member -Ctx $ctx -Key $s.assigned_host
    Line ("- **D:** Promote signal ``$($s.id)`` to a training brief ($($a.name))?  -> REC yes  <approve/hold>")
    $decided = $true
}
if (-not $decided) { Line "- _No open decisions._" }
Line ""

Line "## 2 | TOP SIGNALS"
foreach ($s in @($cfg.signals | Sort-Object priority | Select-Object -First 3)) {
    $a = Find-Member -Ctx $ctx -Key $s.assigned_host
    Line ("- **$($s.headline)** [$($s.priority)] - _why:_ $($s.why_it_matters) -> **$($a.name)**")
}
Line ""

Line "## 3 | IN FLIGHT"
foreach ($e in @($cfg.episodes | Where-Object { $_.status -ne 'published' })) {
    $h = Find-Member -Ctx $ctx -Key $e.host
    Line ("- ``$($e.id)`` *$($e.title)* - stage **$($e.status)** - host $($h.name)")
}
Line ""

Line "## 4 | SHIPPED (last 24h)"
$shipped = @($cfg.episodes | Where-Object { $_.status -eq 'published' })
if ($shipped.Count -gt 0) {
    foreach ($e in $shipped) { Line ("- ``$($e.id)`` *$($e.title)* -> $($e.publish_targets -join ', ')") }
} else { Line "- _Nothing shipped in window._" }
Line ""

Line "## 5 | BROKE / RISKS"
$fails = @()
$logFile = Join-Path $ctx.Logs ('family-' + $today + '.jsonl')
if (Test-Path $logFile) {
    $fails = @(Get-Content $logFile | ForEach-Object { $_ | ConvertFrom-Json } | Where-Object { $_.result -ne 'ok' })
}
if ($fails.Count -gt 0) {
    foreach ($f in $fails) { Line ("- $($f.system) | $($f.task) - **$($f.result)**") }
} else { Line "- _No failures logged._" }
Line ""

Line "## 6 | NEXT 24h"
Line "- Run ``daily-loop.ps1`` | execute approved decisions | queue cutdowns"
Line ""
Line "## 7 | SYSTEM UPGRADE"
Line "- One improvement to the Family OS itself (auto-suggested by the Thinkers)."
Line ""
Line "_Generated by send-family-briefing.ps1 | AI Family OS_"

$outFile = Join-Path $ctx.Briefs ("briefing-$today.md")
$sb.ToString() | Set-Content -Path $outFile -Encoding utf8
Write-Host ("OK Briefing -> {0}" -f $outFile) -ForegroundColor Green
Write-FamilyLog -Ctx $ctx -System 'briefing' -Actor 'MBR-0001' -Task 'generated daily briefing' | Out-Null
