#!/usr/bin/env node
// AI Family OS — the Librarian's chore (delegated, repetitive, free).
// Auto-generates docs/INDEX.md: a map of every doc, skill, tool, course, page + the registry
// counts. Run it after adding files so the index never goes stale.
//   node tools/index-docs.js
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ls = (d, re) => { try { return fs.readdirSync(path.join(ROOT, d)).filter(f => re.test(f)).sort(); } catch { return []; } };
const fam = JSON.parse(fs.readFileSync(path.join(ROOT, 'config', 'family.json'), 'utf8'));

const counts = {
  members: (fam.members || []).length, crews: (fam.crews || []).length,
  pipelines: (fam.pipelines || []).length, tools: (fam.tools || []).length,
  signals: (fam.signals || []).length, episodes: (fam.episodes || []).length,
};
const skills = ls('skills', /.*/).filter(f => fs.existsSync(path.join(ROOT, 'skills', f, 'SKILL.md')) || fs.statSync(path.join(ROOT, 'skills', f)).isDirectory());

let md = `# INDEX — the AI Family OS map (auto-generated)

> Generated by \`node tools/index-docs.js\` on ${new Date().toISOString().slice(0, 10)}. Do not hand-edit.

## Registry (config/family.json)
- ${counts.members} members · ${counts.crews} crews · ${counts.pipelines} pipelines · ${counts.tools} tools · ${counts.signals} signals · **${counts.episodes} episodes**

## Episodes
${(fam.episodes || []).map(e => `- **${e.id}** — ${e.title} _(host ${e.host}, ${e.status})_ → \`${e.script}\``).join('\n')}

## Docs (docs/)
${ls('docs', /\.md$/).map(f => `- \`docs/${f}\``).join('\n')}

## Skills (skills/)
${skills.map(f => `- \`skills/${f}/\``).join('\n')}

## Tools (tools/)
${ls('tools', /\.js$/).map(f => `- \`tools/${f}\``).join('\n')}

## Pages (content/*.html)
${ls('content', /\.html$/).map(f => `- \`content/${f}\``).join('\n')}

## Intel (intel/)
${ls('intel', /\.md$/).map(f => `- \`intel/${f}\``).join('\n')}

## Courses (courses/)
${ls('courses', /.*/).map(f => `- \`courses/${f}/\``).join('\n')}

_The librarian's chore — delegated + automated so the human-readable map never goes stale._
`;

fs.writeFileSync(path.join(ROOT, 'docs', 'INDEX.md'), md);
console.log(`index-docs: wrote docs/INDEX.md — ${counts.episodes} episodes, ${ls('docs', /\.md$/).length} docs, ${ls('content', /\.html$/).length} pages, ${ls('tools', /\.js$/).length} tools.`);
